name: Docker Image CI
env:
  DOCKER_USERNAME: ${{ secrets.UUNAME }} //สร้าง secrets ussername docker hub ไว้ที่ tab settings ของ repository
  DOCKER_PASSWORD: ${{ secrets.SSNAME }} //สร้าง secrets password docker hub ไว้ที่ tab settings ของ repository
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.UUNAME }}
          password: ${{ secrets.SSNAME }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: thitiyan/react-project
